services:
  - type: web
    name: kiyumba-backend
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_FILE
        value: /data/kiyumba_school.db
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
